- hosts: all
  tasks:
  - name: "Copying java Software"
    copy:
      src: "/root/java.rpm"
      dest: "/root"
  - name: "Copying Hadoop Software"
    copy:
      src: "/root/hadoop.rpm"
      dest: "/root"
  - name: "Installing java Software"
    dnf:
      name: "/root/java.rpm"
      state: present
      disable_gpg_check: yes
  - name: "Installing hadoop Software"
    command:
      cmd: "rpm -i /root/hadoop.rpm --force"
- hosts: namenode
  tasks:
  - name: "Creating directory for namenode"
    file:
      path: "/dataspace"
      state: directory
  - name: "Configuring hdfs-site.xml file in namenode"
    blockinfile:
      path: "/etc/hadoop/hdfs-site.xml"
      insertafter: "<configuration>"
      block: |
              <property>
              <name>dfs.name.dir</name>
              <value>/dataspace</value>
              </property>
  - name: "Configuring core-site.xml file in namenode"
    blockinfile:
       path: /etc/hadoop/core-site.xml
       insertafter: "<configuration>"
       block: |
               <property>
               <name>fs.default.name</name>
               <value>hdfs://{{ groups['namenode'][0] }}:9001</value>
               </property>
  - name: "Formating Namenode"
    shell: "echo Y | hadoop namenode -format"
  - name: "Start Namenode service"
    command: "hadoop-daemon.sh start namenode"
- hosts: datanode
  tasks:
  - name: "Creating directory for Datanode"
    file:
      path: "/shared"
      state: directory
  - name: "Configuring hdfs-site.xml in Datanode"
    blockinfile:
      path: "/etc/hadoop/hdfs-site.xml"
      insertafter: "<configuration>"
      block: |
              <property>
              <name>dfs.data.dir</name>
              <value>/shared</value>
              </property>
  - name: "Configure core-site.xml file in Datanode"
    blockinfile:
       path: "/etc/hadoop/core-site.xml"
       insertafter: "<configuration>"
       block: |
               <property>
               <name>fs.default.name</name>
               <value>hdfs://{{ groups['namenode'][0] }}:9001</value>
               </property>
  - name: "Start Datanode service"
    command: "hadoop-daemon.sh start datanode"